### ISSUE TITLE
Event Table and Event Viewer UI experience fatal error when large number of recordings are present 

### ISSUE THREAD

**Issue by Heikin-Ashi** [bobcamera/bobcamera#141] opened 2024-03-13 01:50 UTC
A combination of a tree branch intruding beyond my mask and a lot of fast moving clouds caused BOB to record a whopping 2,362 videos on 3-12-24. More than the Event Viewer & Event Table can manage apparently. Event Grid worked fine though. I'm not sure if this is a bug or just a system limitation. Either way I thought I should report it. 

![Screenshot from 2024-03-12 20-41-37](https://github.com/bobcamera/bobcamera/assets/86312516/916a9852-2f50-4ff7-8713-8430b337522f)

**Comment by Micky-G** [comment] 2024-03-13 09:03
I initially thought this was a duplicate of #128 but its a different php page so valid and needs fixing.

**Comment by Heikin-Ashi** [comment] 2024-03-14 02:30
The sky has been pretty active lately so I now have multiple days where this error has cropped up. Since this effectively disables the Event Viewer and Event table, it makes downloading videos impossible as there is no option to download videos in the Event Grid UI. I've had to copy the entire bobcamera/assets/recordings folder to a new directory and then preview, sort, and save completely outside of the BOB Camera UI.

**Comment by Micky-G** [comment] 2024-03-14 17:41
@Heikin-Ashi I have hard coded a max events setting of 1000, not sure what else to do here. Do you know many events are in the folder to cause that issue to happen?

**Comment by Heikin-Ashi** [comment] 2024-03-16 04:22
@Micky-G It's mostly lightning from the storms and BOB getting tripped up by dark, fast moving clouds against a light background. Also a lot of birds. I made a table summarizing the errors. 
[BOB UI Errors.xlsx](https://github.com/bobcamera/bobcamera/files/14622396/BOB.UI.Errors.xlsx)

**Comment by Micky-G** [comment] 2024-03-21 08:46
Confirmation bug is resolved, hopefully we have put measures in place to reduce events as well.

**Closed** 2024-03-21 08:46 UTC
Labels: bug
